--/*==============================================================*/
--/* Nom de la base :  BIBLIO                                     */
--/* Nom du fichier : install_data_biblio.sql                     */
--/* Nom de SGBD :  ORACLE Version 10g                            */
--/* Date de crÃ©ation :  27/04/2016                               */
--/* Auteurs : Laetitia Laleye & Jean-Jules Dormevil              */                                                    */
--/*==============================================================*/


-- Commandes pour purger la base
DELETE FROM UTILISATEUR ;
DELETE FROM  ADHERENTGENERAL ;
DELETE FROM  EMPLOYE ;
DELETE FROM  THEME ;
DELETE FROM  EDITEUR ;
DELETE FROM  LIVRE ;
DELETE FROM  ADHERENT ;
DELETE FROM  EXEMPLAIRE ;
DELETE FROM  EMPRUNTENCOURS ;
DELETE FROM  AUTEUR ;
DELETE FROM  AUTEUR_LIVRE ;
DELETE FROM  EMPRUNTARCHIVE ;




-- Insertion dans les tables 

insert into ADHERENTGENERAL (NBMAXPRETS, DUREEMAXPRET) values (3, 15);


insert into THEME (CODETHEME, LIBELLE, PARENT) values ('0', 'Sciences et connaissance', '');
insert into THEME (CODETHEME, LIBELLE, PARENT) values ('1', 'Philosophie et psychologie', '');
insert into THEME (CODETHEME, LIBELLE, PARENT) values ('2', 'Religion. Théologie', '');
insert into THEME (CODETHEME, LIBELLE, PARENT) values ('3', 'Sciences sociales', '');
insert into THEME (CODETHEME, LIBELLE, PARENT) values ('4', 'inoccupée', '');
insert into THEME (CODETHEME, LIBELLE, PARENT) values ('5', 'Mathématiques, Sciences exactes et naturelles', '');
insert into THEME (CODETHEME, LIBELLE, PARENT) values ('6', 'Sciences appliquées. Médecine. Technologie', '');
insert into THEME (CODETHEME, LIBELLE, PARENT) values ('7', 'Arts. Divertissements. Sports', '');
insert into THEME (CODETHEME, LIBELLE, PARENT) values ('8', 'Langue. Linguistique. Littérature', '');
insert into THEME (CODETHEME, LIBELLE, PARENT) values ('9', 'Géographie. Biographie. Histoire', '');
insert into THEME (CODETHEME, LIBELLE, PARENT) values ('81','Linguistique et langues', '8');


insert into EDITEUR (IDEDITEUR, NOMEDITEUR, VILLE) values (1, 'Hachette', 'Paris');
insert into EDITEUR (IDEDITEUR, NOMEDITEUR, VILLE) values (2, 'Gallimard', 'Paris');
insert into EDITEUR (IDEDITEUR, NOMEDITEUR, VILLE) values (3, 'Robert Laffont', 'Paris');
insert into EDITEUR (IDEDITEUR, NOMEDITEUR, VILLE) values (4, 'Soleil', 'Paris');
insert into EDITEUR (IDEDITEUR, NOMEDITEUR, VILLE) values (5, 'Bloomsbury Publishing', 'Londres');


insert into LIVRE (ISBN, TITRE, ANNEEPARUTION, NBPAGES, IDEDITEUR, CODETHEME) values ('2J0RNVA0S2Q1I', 'The Philosopher''s Stone', 1997, 400, 5, '8');
insert into LIVRE (ISBN, TITRE, ANNEEPARUTION, NBPAGES, IDEDITEUR, CODETHEME) values ('V T12N1GOHJTO', 'The Chamber of Secrets', 1998, 550, 5, '8');
insert into LIVRE (ISBN, TITRE, ANNEEPARUTION, NBPAGES, IDEDITEUR, CODETHEME) values ('VT E677B06ACV', 'The Prisoner of Azkaban', 1999, 564, 5, '8');
insert into LIVRE (ISBN, TITRE, ANNEEPARUTION, NBPAGES, IDEDITEUR, CODETHEME) values ('RHI4D9O30NE05', 'The Goblet of Fire', 2000, 700, 5, '8');
insert into LIVRE (ISBN, TITRE, ANNEEPARUTION, NBPAGES, IDEDITEUR, CODETHEME) values ('Q4LGLT6IL SE2', 'The Order of the Phoenix', 2003, 652, 5, '8');
insert into LIVRE (ISBN, TITRE, ANNEEPARUTION, NBPAGES, IDEDITEUR, CODETHEME) values ('VK G M21IQSWM', 'The Half-Blood Prince', 2005, 670, 5, '8');
insert into LIVRE (ISBN, TITRE, ANNEEPARUTION, NBPAGES, IDEDITEUR, CODETHEME) values ('6 U5R8EATAWOQ', 'The Deathly Hallows', 2007, 950, 5, '8');
insert into LIVRE (ISBN, TITRE, ANNEEPARUTION, NBPAGES, IDEDITEUR, CODETHEME) values ('7UO3F39XQQC2O', 'Les Maîtres Inquisiteurs', 2016, 55, 4, '7');
insert into LIVRE (ISBN, TITRE, ANNEEPARUTION, NBPAGES, IDEDITEUR, CODETHEME) values ('PGFT EJ2YGQ57', 'Les Maîtres Inquisiteurs', 2016, 250, 2, '1');
insert into LIVRE (ISBN, TITRE, ANNEEPARUTION, NBPAGES, IDEDITEUR, CODETHEME) values ('M8RSEOG C477I', 'Mon Atlas du Monde', 2016, 75, 1, '9');

insert into AUTEUR (IDAUTEUR, NOM, PRENOM) values (1, 'Rowling', 'J.K.');
insert into AUTEUR (IDAUTEUR, NOM, PRENOM) values (2, 'Dewey', 'John');
insert into AUTEUR (IDAUTEUR, NOM, PRENOM) values (3, 'Morrison', 'Toni');
insert into AUTEUR (IDAUTEUR, NOM, PRENOM) values (4, 'Angelou', 'Maya');
insert into AUTEUR (IDAUTEUR, NOM, PRENOM) values (5, 'Woolf', 'Virginia');


insert into UTILISATEUR (IDUTILISATEUR,NOM, PRENOM, PWD, PSEUDONYME, DATENAISSANCE, SEXE, CATEGORIEUTILISATEUR) values (1,'Her', 'Xavier', 'FMBNF9F41LSUP3T', '635RG5 3Y8KKCU8VE693', '12/04/1973', 'M', 'ADHERENT');
insert into UTILISATEUR (IDUTILISATEUR,NOM, PRENOM, PWD, PSEUDONYME, DATENAISSANCE, SEXE, CATEGORIEUTILISATEUR) values (2,'Keyssan', 'Parjine', 'X 505OWY33XAFEG', 'PMEJ1FADO 3SSL2L7T1W', '21/02/1980', 'F', 'ADHERENT');
insert into UTILISATEUR (IDUTILISATEUR,NOM, PRENOM, PWD, PSEUDONYME, DATENAISSANCE, SEXE, CATEGORIEUTILISATEUR) values (3,'Doua', 'Ismael', '6JXMMQMC3GO6WGV', '99JIJ9WC6OM1V0FV5OOT', '20/06/1984', 'M', 'ADHERENT');
insert into UTILISATEUR (IDUTILISATEUR,NOM, PRENOM, PWD, PSEUDONYME, DATENAISSANCE, SEXE, CATEGORIEUTILISATEUR) values (4,'Marie-Joseph', 'Carthy', 'YIP7IGVL5BS87MF', 'SB99BO9ACHCM7YPAQA8L', '08/08/1991', 'M', 'EMPLOYE');
insert into UTILISATEUR (IDUTILISATEUR,NOM, PRENOM, PWD, PSEUDONYME, DATENAISSANCE, SEXE, CATEGORIEUTILISATEUR) values (5,'Dormevil', 'Jean-Jules', 'BKUANDBN2JW5XL5', 'PT9HKKFRA3U6VX213JE2', '31/01/1989', 'M', 'EMPLOYE');
insert into UTILISATEUR (IDUTILISATEUR,NOM, PRENOM, PWD, PSEUDONYME, DATENAISSANCE, SEXE, CATEGORIEUTILISATEUR) values (6,'Dormevil', 'Jean-Jules', 'BKUANDBN2JW5XL5', 'PT9HKKFRA3U6VX213JE2', '31/01/1989', 'M', 'EMPLOYE');
insert into UTILISATEUR (IDUTILISATEUR,NOM, PRENOM, PWD, PSEUDONYME, DATENAISSANCE, SEXE, CATEGORIEUTILISATEUR) values (7,'Laleye', 'Laetitia', 'BKUANDBN2JW5XL5', 'PT9HKKFRA3U6VX213JE2', '30/06/1990', 'F', 'EMPLOYE');
insert into UTILISATEUR (IDUTILISATEUR,NOM, PRENOM, PWD, PSEUDONYME, DATENAISSANCE, SEXE, CATEGORIEUTILISATEUR) values (8,'Chinapa', 'Edwin', 'BKUANDBN2JW5XL5', 'PT9HKKFRA3U6VX213JE2', '28/02/1980', 'M', 'ADHERENT');
insert into UTILISATEUR (IDUTILISATEUR,NOM, PRENOM, PWD, PSEUDONYME, DATENAISSANCE, SEXE, CATEGORIEUTILISATEUR) values (9,'Dormevil', 'Gael', 'BKUANDBN2JW5XL5', 'PT9HKKFRA3U6VX213JE2', '29/04/1995', 'M', 'ADHERENT');
insert into UTILISATEUR (IDUTILISATEUR, NOM, PRENOM, PWD, PSEUDONYME, DATENAISSANCE, SEXE, CATEGORIEUTILISATEUR) values (10,'Ferhat', 'Salah', 'BKUANDBN2JW5XL5', 'PT9HKKFRA3U6VX213JE2', '18/10/1981', 'M', 'EMPLOYE');


insert into AUTEUR_LIVRE (ISBN, IDAUTEUR, ORDREAUTEUR) values ('2J0RNVA0S2Q1I', 1, 1);
insert into AUTEUR_LIVRE (ISBN, IDAUTEUR, ORDREAUTEUR) values ('V T12N1GOHJTO', 2, 1);
insert into AUTEUR_LIVRE (ISBN, IDAUTEUR, ORDREAUTEUR) values ('VT E677B06ACV', 3, 2);
insert into AUTEUR_LIVRE (ISBN, IDAUTEUR, ORDREAUTEUR) values ('RHI4D9O30NE05', 4, 1);
insert into AUTEUR_LIVRE (ISBN, IDAUTEUR, ORDREAUTEUR) values ('Q4LGLT6IL SE2', 5, 1);

insert into EXEMPLAIRE (IDEXEMPLAIRE, DATEACHAT, STATUS, ISBN ) values (1,'12/02/1910', 'DISPONIBLE', '2J0RNVA0S2Q1I');
insert into EXEMPLAIRE (IDEXEMPLAIRE, DATEACHAT, STATUS, ISBN ) values (2,'12/02/1910', 'SUPPRIME', 'V T12N1GOHJTO');
insert into EXEMPLAIRE (IDEXEMPLAIRE, DATEACHAT, STATUS, ISBN ) values (3,'12/02/1910', 'PRETE', 'VT E677B06ACV');
insert into EXEMPLAIRE (IDEXEMPLAIRE, DATEACHAT, STATUS, ISBN ) values (4,'12/02/1910', 'DISPONIBLE', 'RHI4D9O30NE05');
insert into EXEMPLAIRE (IDEXEMPLAIRE, DATEACHAT, STATUS, ISBN ) values (5,'12/02/1910', 'DISPONIBLE', 'Q4LGLT6IL SE2');
insert into EXEMPLAIRE (IDEXEMPLAIRE, DATEACHAT, STATUS, ISBN ) values (6,'12/02/1910', 'DISPONIBLE', 'VK G M21IQSWM');
insert into EXEMPLAIRE (IDEXEMPLAIRE, DATEACHAT, STATUS, ISBN ) values (7,'12/02/1910', 'PRETE', '6 U5R8EATAWOQ' );
insert into EXEMPLAIRE (IDEXEMPLAIRE, DATEACHAT, STATUS, ISBN ) values (8,'12/02/1910', 'DISPONIBLE','7UO3F39XQQC2O');
insert into EXEMPLAIRE (IDEXEMPLAIRE, DATEACHAT, STATUS, ISBN ) values (9,'12/02/1910', 'PRETE', 'PGFT EJ2YGQ57');
insert into EXEMPLAIRE (IDEXEMPLAIRE, DATEACHAT, STATUS, ISBN ) values (10,'12/02/1910', 'DISPONIBLE', 'M8RSEOG C477I');

insert into ADHERENT (IDUTILISATEUR, TELEPHONE) values (6, 0611071101);
insert into ADHERENT (IDUTILISATEUR, TELEPHONE) values (7, 0645789523);
insert into ADHERENT (IDUTILISATEUR, TELEPHONE) values (5, 0645779524);
insert into ADHERENT (IDUTILISATEUR, TELEPHONE) values (9, 0645789525);
insert into ADHERENT (IDUTILISATEUR, TELEPHONE) values (8, 0645789526);


insert into EMPRUNTENCOURS (IDEXEMPLAIRE, IDUTILISATEUR, DATEEMPRUNT) values (3, 3, '12/02/2015');
insert into EMPRUNTENCOURS (IDEXEMPLAIRE, IDUTILISATEUR, DATEEMPRUNT) values (5, 9, '21/03/2016');
insert into EMPRUNTENCOURS (IDEXEMPLAIRE, IDUTILISATEUR, DATEEMPRUNT) values (10, 8, '06/01/2016');
insert into EMPRUNTENCOURS (IDEXEMPLAIRE, IDUTILISATEUR, DATEEMPRUNT) values (2, 1, '12/12/2015');
insert into EMPRUNTENCOURS (IDEXEMPLAIRE, IDUTILISATEUR, DATEEMPRUNT) values (4, 4, '17/02/2016');
insert into EMPRUNTENCOURS (IDEXEMPLAIRE, IDUTILISATEUR, DATEEMPRUNT) values (7, 5, '12/03/2016');
insert into EMPRUNTENCOURS (IDEXEMPLAIRE, IDUTILISATEUR, DATEEMPRUNT) values (6, 9, '28/02/2016');
insert into EMPRUNTENCOURS (IDEXEMPLAIRE, IDUTILISATEUR, DATEEMPRUNT) values (8, 1, '12/01/2016');
insert into EMPRUNTENCOURS (IDEXEMPLAIRE, IDUTILISATEUR, DATEEMPRUNT) values (9, 2, '12/04/2016');
insert into EMPRUNTENCOURS (IDEXEMPLAIRE, IDUTILISATEUR, DATEEMPRUNT) values (1, 9, '12/02/2016');

insert into EMPRUNTARCHIVE (IDEMPRUNTARCHIVE, IDEXEMPLAIRE, IDUTILISATEUR, DATERESTITUTIONEFF, DATEEMPRUNT) values (1,5, 4, '28/04/2016', '12/02/2015');
insert into EMPRUNTARCHIVE (IDEMPRUNTARCHIVE, IDEXEMPLAIRE, IDUTILISATEUR, DATERESTITUTIONEFF, DATEEMPRUNT) values (2,6, 4, '28/04/2016', '12/02/2015');
insert into EMPRUNTARCHIVE (IDEMPRUNTARCHIVE, IDEXEMPLAIRE, IDUTILISATEUR, DATERESTITUTIONEFF, DATEEMPRUNT) values (3,3, 2, '28/04/2016', '12/02/2015');
insert into EMPRUNTARCHIVE (IDEMPRUNTARCHIVE, IDEXEMPLAIRE, IDUTILISATEUR, DATERESTITUTIONEFF, DATEEMPRUNT) values (4,10, 6,'28/04/2016', '12/02/2015');
insert into EMPRUNTARCHIVE (IDEMPRUNTARCHIVE, IDEXEMPLAIRE, IDUTILISATEUR, DATERESTITUTIONEFF, DATEEMPRUNT) values (5,9, 9, '28/04/2016', '12/02/2015');
insert into EMPRUNTARCHIVE (IDEMPRUNTARCHIVE, IDEXEMPLAIRE, IDUTILISATEUR, DATERESTITUTIONEFF, DATEEMPRUNT) values (6,9, 7, '28/04/2016', '12/02/2015');
insert into EMPRUNTARCHIVE (IDEMPRUNTARCHIVE, IDEXEMPLAIRE, IDUTILISATEUR, DATERESTITUTIONEFF, DATEEMPRUNT) values (7,5, 2, '28/04/2016', '12/02/2015');
insert into EMPRUNTARCHIVE (IDEMPRUNTARCHIVE, IDEXEMPLAIRE, IDUTILISATEUR, DATERESTITUTIONEFF, DATEEMPRUNT) values (8,3, 4, '28/04/2016', '12/02/2015');
insert into EMPRUNTARCHIVE (IDEMPRUNTARCHIVE, IDEXEMPLAIRE, IDUTILISATEUR, DATERESTITUTIONEFF, DATEEMPRUNT) values (9,5, 8, '28/04/2016', '12/02/2015');
insert into EMPRUNTARCHIVE (IDEMPRUNTARCHIVE, IDEXEMPLAIRE, IDUTILISATEUR, DATERESTITUTIONEFF, DATEEMPRUNT) values (10,8, 8, '28/04/2016', '12/02/2015');

insert into EMPLOYE (IDUTILISATEUR, CODEMATRICULE, CATEGORIEEMPLOYE) values (3, 'L3018J2QRCOXKJY', 'BIBLIOTHECAIRE');
insert into EMPLOYE (IDUTILISATEUR, CODEMATRICULE, CATEGORIEEMPLOYE) values (7, 'RMGH1CLMSLIHJO4', 'GESTIONNAIRE_DE_FOND');
insert into EMPLOYE (IDUTILISATEUR, CODEMATRICULE, CATEGORIEEMPLOYE) values (5, 'ET4855 VMBAXNY4', 'BIBLIOTHECAIRE');
insert into EMPLOYE (IDUTILISATEUR, CODEMATRICULE, CATEGORIEEMPLOYE) values (9, '89WTSOCXACLEJFE', 'BIBLIOTHECAIRE');
insert into EMPLOYE (IDUTILISATEUR, CODEMATRICULE, CATEGORIEEMPLOYE) values (8, 'H K1X1S62AGY58M', 'BIBLIOTHECAIRE');
insert into EMPLOYE (IDUTILISATEUR, CODEMATRICULE, CATEGORIEEMPLOYE) values (4, '5NQ8Q Y0Y3S52L8', 'BIBLIOTHECAIRE');
insert into EMPLOYE (IDUTILISATEUR, CODEMATRICULE, CATEGORIEEMPLOYE) values (6, 'X WLQRX8PDOQANV', 'RESPONSABLE');
insert into EMPLOYE (IDUTILISATEUR, CODEMATRICULE, CATEGORIEEMPLOYE) values (2, 'TYU44CN9U90MYI ', 'BIBLIOTHECAIRE');
insert into EMPLOYE (IDUTILISATEUR, CODEMATRICULE, CATEGORIEEMPLOYE) values (1, '6VDGPX5E6R55UHE', 'BIBLIOTHECAIRE');
insert into EMPLOYE (IDUTILISATEUR, CODEMATRICULE, CATEGORIEEMPLOYE) values (10, 'NXL2Y 981NJ78PH', 'BIBLIOTHECAIRE');

commit;